### ISSUE TITLE
Adding electric field and dielectric constant from the command line

### ISSUE THREAD

**Issue by Biswarupash** [sussmanLab/open-Qmin#3]
Hello,

Currently one can add a magnetic field from the command line using --hField. Is it possible to add an electric field in a similar way, i.e., --eFieldX/Y/Z? Can we change the dielectric constant or permittivity? It would be nice if we set the electric field from the command line. In the GUI, I can see the options for electric field. Can we do it from the terminal?

Thank you in advance.

**Comment by DanielMSussman** [comment]
Done!

commit 617c1e4b54c05a39a1a4db01cfb70dff151104b5
